
Devoir : Création d'un site web de mode avec le système MVC

Objectif
Créer un site web de mode en utilisant le modèle MVC avec Go pour le backend, et HTML, CSS, ainsi que JavaScript (optionnel) pour le frontend. Le site doit comporter 10 pages distinctes.

Schématiser le modèle MVC dans le readme.


1. **Page d'accueil**

   - Descriptif de ce que le site propose.
   - À propos du site.
   - Images au centre de la page.

2. **Page de services**
   - Liste des services proposés par le site.

3. **Page catalogue**
   - Différents modèles déjà réalisés avec leurs descriptions et images.

4. **Page d'achat et commande**

   - Formulaire pour passer une commande.

5. **Page de contact**
   - Formulaire de contact pour les utilisateurs.

6. **Page de l'équipe**
   - Présentation des membres de l'équipe.

7. **Page de blog**
   - Articles de blog sur les tendances de la mode.

8. **Page de témoignages**

   - Témoignages des clients satisfaits.

9. **Page FAQ**
   - Réponses aux questions fréquemment posées.

10. **Page d'événements**
    - Informations sur les événements et promotions à venir.